version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: swarmfill_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: swarmfill_db
      POSTGRES_USER: swarmfill_user
      POSTGRES_PASSWORD: swarmfill123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d/
    networks:
      - swarmfill_network

  redis:
    image: redis:7-alpine
    container_name: swarmfill_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - swarmfill_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: swarmfill-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: swarmfill_db
      DB_USER: swarmfill_user
      DB_PASSWORD: swarmfill123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key
      FRONTEND_URLS: http://localhost:19006,http://localhost:3001
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/src:/app/src
      - ./backend/logs:/app/logs
    networks:
      - swarmfill_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: swarmfill_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@swarmfill.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - swarmfill_network

volumes:
  postgres_data:
  redis_data:

networks:
  swarmfill_network:
    driver: bridge
